server:
 port: 8081
 
spring: 
 application:
  name: activity-service
 data:
  mongodb:
   host: localhost 
   port: 27017
   database: fitness_activity_db

eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka/

user-service:
 base-url: http://USER-SERVICE