#server:
# port: 8080
 
spring:
  application:
    name: user-service
  config:
   import: optional:configserver:http://localhost:8888
  
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/fitness_user_db
#    username: root
#    password: ${userService.db.password}
#
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQLDialect
#
#eureka:
# client:
#  serviceUrl:
#   defaultZone: http://localhost:8761/eureka/