server:
 port: 8082
 
spring:
 application:
  name: ai-ervice
 data:
  mongodb:
   host: localhost 
   port: 27017 
   database: fitness_activity_db


eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka/